version: '3.8'

services:
  database:
    image: mysql
    container_name: gdsc
    environment:
    - MYSQL_DATABASE=1week
    - MYSQL_ROOT_PASSWORD=1234
    - TZ= Asia/Seoul
    ports:
      - '3307:3306'
    # volumes:
    #   - ./db/data:/var/lib/mysql
  
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./build/libs/*.jar
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://gdsc:3306/1week?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - database
